# Generated by Django 4.0.3 on 2022-03-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_profesion_remove_estudiante_profesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesion',
            new_name='Profesor',
        ),
    ]
