# Generated by Django 4.0.3 on 2022-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_rename_profesion_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
